name: Tests

on: [push, workflow_dispatch]

env:
  CARGO_TERM_COLOR: always

jobs:
  loom_tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Cache build artifacts
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-loom-${{ hashFiles('**/Cargo.toml') }}

      - name: Lint
        run: make lint

      - name: Run Loom tests
        run: make loom

  tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Cache build artifacts
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-tests-${{ hashFiles('**/Cargo.toml') }}

      - name: Lint
        run: make lint

      - name: Run tests
        run: make test

  benchmarks:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Cache build artifacts
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-benchmarks-${{ hashFiles('**/Cargo.toml') }}

      - name: Lint
        run: make lint

      - name: Run benchmarks
        run: cargo bench -- --output-format bencher | tee output.txt

      # Download previous benchmark result from cache (if exists)
      - name: Download previous benchmark data
        uses: actions/cache@v1
        with:
          path: ./cache
          key: ${{ runner.os }}-benchmark

      - name: Store benchmark result
        uses: rhysd/github-action-benchmark@v1
        with:
          tool: "cargo"
          output-file-path: output.txt
          # Where the previous data file is stored
          external-data-json-path: ./cache/benchmark-data.json
          alert-threshold: "130%"
          # GitHub API token to make a commit comment
          github-token: ${{ secrets.GITHUB_TOKEN }}
          # Enable alert commit comment
          comment-on-alert: true
          fail-on-alert: false
