name: Tests

on: [push, workflow_dispatch]

env:
  CARGO_TERM_COLOR: always

jobs:
  loom_tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Cache build artifacts
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-loom-${{ hashFiles('**/Cargo.toml') }}

      - name: Lint
        run: make lint

      - name: Run Loom tests
        run: make loom

  tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Cache build artifacts
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-tests-${{ hashFiles('**/Cargo.toml') }}

      - name: Lint
        run: make lint

      - name: Run tests
        run: make test
